/* eslint-disable */
import * as types from './graphql';
import { TypedDocumentNode as DocumentNode } from '@graphql-typed-document-node/core';

/**
 * Map of all GraphQL operations in the project.
 *
 * This map has several performance disadvantages:
 * 1. It is not tree-shakeable, so it will include all operations in the project.
 * 2. It is not minifiable, so the string of a GraphQL query will be multiple times inside the bundle.
 * 3. It does not support dead code elimination, so it will add unused operations.
 *
 * Therefore it is highly recommended to use the babel or swc plugin for production.
 * Learn more about it here: https://the-guild.dev/graphql/codegen/plugins/presets/preset-client#reducing-bundle-size
 */
type Documents = {
  '\n  query HistoricalPairMetrics(\n    $where: HistoricalPairMetricsWhereInput\n    $orderBy: [HistoricalPairMetricsOrderByInput!]\n  ) {\n    historicalPairMetrics(where: $where, orderBy: $orderBy, limit: 350) {\n      id\n      date\n      pairAddress\n      token0\n      token1\n      reserve0\n      reserve1\n      liquidityUSD\n      lpTotalSupply\n      lpTotalLocked\n      token0Price\n      token1Price\n      txCount24h\n      txCountTotal\n      liquidityProviderCount\n      lastUpdatedAt\n      lastUpdatedAtBlockTimestamp\n    }\n  }\n': typeof types.HistoricalPairMetricsDocument;
  '\n  query PairById($pairByIdId: String!) {\n    pairById(id: $pairByIdId) {\n      id\n      token0 {\n        id\n        symbol\n        name\n        decimals\n        totalSupply\n        circulationSupply\n        holders\n        tokenPicture\n        tokenMetrics {\n          id\n          tokenAddress\n          priceUSD\n          priceETH\n          price24hDelta\n          marketCapUSD\n          fdv\n          tradeVolume24h\n          tradeVolumeUSD24h\n          tradeVolumeETH24h\n          txCount24h\n          txCountTotal\n          totalLiquidityAllPairs\n          totalLiquidityAllPairsUSD\n          lastUpdatedAt\n          lastUpdatedAtBlockTimestamp\n        }\n        factoryAddress\n        lastUpdatedAt\n        lastUpdatedAtBlockTimestamp\n      }\n      token1 {\n        id\n        symbol\n        name\n        tokenPicture\n        decimals\n        totalSupply\n        circulationSupply\n        holders\n        tokenMetrics {\n          id\n          tokenAddress\n          priceUSD\n          priceETH\n          price24hDelta\n          marketCapUSD\n          fdv\n          tradeVolume24h\n          tradeVolumeUSD24h\n          tradeVolumeETH24h\n          txCount24h\n          txCountTotal\n          totalLiquidityAllPairs\n          totalLiquidityAllPairsUSD\n          lastUpdatedAt\n          lastUpdatedAtBlockTimestamp\n        }\n        factoryAddress\n        lastUpdatedAt\n        lastUpdatedAtBlockTimestamp\n      }\n      token0Id\n      token1Id\n      reserve0\n      reserve1\n      liquidityUSD\n      liquidity24hDelta\n      lpTotalSupply\n      lpTotalLocked\n      lpDecimals\n      token0Price\n      token1Price\n      txCount24h\n      txCountTotal\n      tradeVolume24h\n      tradeVolumeUSD24h\n      tradeVolumeETH24h\n      tradeVolume24hDelta\n      fees24h\n      feesUSD24h\n      feesETH24h\n      fees24hDelta\n      createdAtTimestamp\n      createdAtBlockNumber\n      liquidityProviderCount\n      factoryAddress\n      lastUpdatedAt\n      lastUpdatedAtBlockTimestamp\n    }\n  }\n': typeof types.PairByIdDocument;
  '\n  query GetPairPricesQuery(\n    $maxPoints: Int!\n    $from: String!\n    $to: String!\n    $token0Address: String!\n    $token1Address: String!\n  ) {\n    pairPrices(\n      maxPoints: $maxPoints\n      to: $to\n      from: $from\n      token0Address: $token0Address\n      token1Address: $token1Address\n    ) {\n      token0 {\n        tokenAddress\n        tokenPrice\n        tokenPriceUsd\n      }\n      token1 {\n        tokenAddress\n        tokenPrice\n        tokenPriceUsd\n      }\n      timestamp\n    }\n  }\n': typeof types.GetPairPricesQueryDocument;
  '\n  query Pairs(\n    $where: PairWhereInput\n    $orderBy: [PairOrderByInput!]\n    $offset: Int\n    $limit: Int\n  ) {\n    pairs(where: $where, orderBy: $orderBy, offset: $offset, limit: $limit) {\n      id\n      token0 {\n        id\n        symbol\n        name\n        decimals\n        totalSupply\n        circulationSupply\n        holders\n        tokenPicture\n        tokenMetrics {\n          id\n          tokenAddress\n          priceUSD\n          priceETH\n          price24hDelta\n          marketCapUSD\n          fdv\n          tradeVolume24h\n          tradeVolumeUSD24h\n          tradeVolumeETH24h\n          txCount24h\n          txCountTotal\n          totalLiquidityAllPairs\n          totalLiquidityAllPairsUSD\n          lastUpdatedAt\n          lastUpdatedAtBlockTimestamp\n        }\n        factoryAddress\n        lastUpdatedAt\n        lastUpdatedAtBlockTimestamp\n      }\n      token1 {\n        id\n        symbol\n        name\n        decimals\n        totalSupply\n        circulationSupply\n        holders\n        tokenPicture\n        tokenMetrics {\n          id\n          tokenAddress\n          priceUSD\n          priceETH\n          price24hDelta\n          marketCapUSD\n          fdv\n          tradeVolume24h\n          tradeVolumeUSD24h\n          tradeVolumeETH24h\n          txCount24h\n          txCountTotal\n          totalLiquidityAllPairs\n          totalLiquidityAllPairsUSD\n          lastUpdatedAt\n          lastUpdatedAtBlockTimestamp\n        }\n        factoryAddress\n        lastUpdatedAt\n        lastUpdatedAtBlockTimestamp\n      }\n      token0Id\n      token1Id\n      reserve0\n      reserve1\n      liquidityUSD\n      liquidity24hDelta\n      lpTotalSupply\n      lpTotalLocked\n      lpDecimals\n      token0Price\n      token1Price\n      txCount24h\n      txCountTotal\n      tradeVolume24h\n      tradeVolumeUSD24h\n      tradeVolumeETH24h\n      tradeVolume24hDelta\n      fees24h\n      feesUSD24h\n      feesETH24h\n      fees24hDelta\n      createdAtTimestamp\n      createdAtBlockNumber\n      liquidityProviderCount\n      factoryAddress\n      lastUpdatedAt\n      lastUpdatedAtBlockTimestamp\n    }\n  }\n': typeof types.PairsDocument;
  '\n  query CurrentLiquidityPositions(\n    $where: CurrentLiquidityPositionWhereInput\n    $orderBy: [CurrentLiquidityPositionOrderByInput!]\n    $offset: Int\n    $limit: Int\n  ) {\n    currentLiquidityPositions(\n      where: $where\n      orderBy: $orderBy\n      offset: $offset\n      limit: $limit\n    ) {\n      id\n      user {\n        id\n        usdSwapped\n        swapsAmount\n        lastUpdatedAt\n        lastUpdatedAtBlockTimestamp\n      }\n      pair {\n        id\n        token0 {\n          id\n          symbol\n          name\n          decimals\n          totalSupply\n          circulationSupply\n          holders\n          tokenMetrics {\n            id\n            tokenAddress\n            priceUSD\n            priceETH\n            price24hDelta\n            marketCapUSD\n            fdv\n            tradeVolume24h\n            tradeVolumeUSD24h\n            tradeVolumeETH24h\n            txCount24h\n            txCountTotal\n            totalLiquidityAllPairs\n            totalLiquidityAllPairsUSD\n            lastUpdatedAt\n            lastUpdatedAtBlockTimestamp\n          }\n          factoryAddress\n          lastUpdatedAt\n          lastUpdatedAtBlockTimestamp\n        }\n        token1 {\n          id\n          symbol\n          name\n          decimals\n          totalSupply\n          circulationSupply\n          holders\n          tokenMetrics {\n            id\n            tokenAddress\n            priceUSD\n            priceETH\n            price24hDelta\n            marketCapUSD\n            fdv\n            tradeVolume24h\n            tradeVolumeUSD24h\n            tradeVolumeETH24h\n            txCount24h\n            txCountTotal\n            totalLiquidityAllPairs\n            totalLiquidityAllPairsUSD\n            lastUpdatedAt\n            lastUpdatedAtBlockTimestamp\n          }\n          factoryAddress\n          lastUpdatedAt\n          lastUpdatedAtBlockTimestamp\n        }\n        token0Id\n        token1Id\n        reserve0\n        reserve1\n        liquidityUSD\n        liquidity24hDelta\n        lpTotalSupply\n        lpTotalLocked\n        lpDecimals\n        token0Price\n        token1Price\n        txCount24h\n        txCountTotal\n        tradeVolume24h\n        tradeVolumeUSD24h\n        tradeVolumeETH24h\n        tradeVolume24hDelta\n        fees24h\n        feesUSD24h\n        feesETH24h\n        fees24hDelta\n        createdAtTimestamp\n        createdAtBlockNumber\n        liquidityProviderCount\n        factoryAddress\n        lastUpdatedAt\n        lastUpdatedAtBlockTimestamp\n      }\n      liquidityTokenBalance\n      lastUpdatedAt\n      lastUpdatedAtBlockTimestamp\n    }\n  }\n': typeof types.CurrentLiquidityPositionsDocument;
};
const documents: Documents = {
  '\n  query HistoricalPairMetrics(\n    $where: HistoricalPairMetricsWhereInput\n    $orderBy: [HistoricalPairMetricsOrderByInput!]\n  ) {\n    historicalPairMetrics(where: $where, orderBy: $orderBy, limit: 350) {\n      id\n      date\n      pairAddress\n      token0\n      token1\n      reserve0\n      reserve1\n      liquidityUSD\n      lpTotalSupply\n      lpTotalLocked\n      token0Price\n      token1Price\n      txCount24h\n      txCountTotal\n      liquidityProviderCount\n      lastUpdatedAt\n      lastUpdatedAtBlockTimestamp\n    }\n  }\n':
    types.HistoricalPairMetricsDocument,
  '\n  query PairById($pairByIdId: String!) {\n    pairById(id: $pairByIdId) {\n      id\n      token0 {\n        id\n        symbol\n        name\n        decimals\n        totalSupply\n        circulationSupply\n        holders\n        tokenPicture\n        tokenMetrics {\n          id\n          tokenAddress\n          priceUSD\n          priceETH\n          price24hDelta\n          marketCapUSD\n          fdv\n          tradeVolume24h\n          tradeVolumeUSD24h\n          tradeVolumeETH24h\n          txCount24h\n          txCountTotal\n          totalLiquidityAllPairs\n          totalLiquidityAllPairsUSD\n          lastUpdatedAt\n          lastUpdatedAtBlockTimestamp\n        }\n        factoryAddress\n        lastUpdatedAt\n        lastUpdatedAtBlockTimestamp\n      }\n      token1 {\n        id\n        symbol\n        name\n        tokenPicture\n        decimals\n        totalSupply\n        circulationSupply\n        holders\n        tokenMetrics {\n          id\n          tokenAddress\n          priceUSD\n          priceETH\n          price24hDelta\n          marketCapUSD\n          fdv\n          tradeVolume24h\n          tradeVolumeUSD24h\n          tradeVolumeETH24h\n          txCount24h\n          txCountTotal\n          totalLiquidityAllPairs\n          totalLiquidityAllPairsUSD\n          lastUpdatedAt\n          lastUpdatedAtBlockTimestamp\n        }\n        factoryAddress\n        lastUpdatedAt\n        lastUpdatedAtBlockTimestamp\n      }\n      token0Id\n      token1Id\n      reserve0\n      reserve1\n      liquidityUSD\n      liquidity24hDelta\n      lpTotalSupply\n      lpTotalLocked\n      lpDecimals\n      token0Price\n      token1Price\n      txCount24h\n      txCountTotal\n      tradeVolume24h\n      tradeVolumeUSD24h\n      tradeVolumeETH24h\n      tradeVolume24hDelta\n      fees24h\n      feesUSD24h\n      feesETH24h\n      fees24hDelta\n      createdAtTimestamp\n      createdAtBlockNumber\n      liquidityProviderCount\n      factoryAddress\n      lastUpdatedAt\n      lastUpdatedAtBlockTimestamp\n    }\n  }\n':
    types.PairByIdDocument,
  '\n  query GetPairPricesQuery(\n    $maxPoints: Int!\n    $from: String!\n    $to: String!\n    $token0Address: String!\n    $token1Address: String!\n  ) {\n    pairPrices(\n      maxPoints: $maxPoints\n      to: $to\n      from: $from\n      token0Address: $token0Address\n      token1Address: $token1Address\n    ) {\n      token0 {\n        tokenAddress\n        tokenPrice\n        tokenPriceUsd\n      }\n      token1 {\n        tokenAddress\n        tokenPrice\n        tokenPriceUsd\n      }\n      timestamp\n    }\n  }\n':
    types.GetPairPricesQueryDocument,
  '\n  query Pairs(\n    $where: PairWhereInput\n    $orderBy: [PairOrderByInput!]\n    $offset: Int\n    $limit: Int\n  ) {\n    pairs(where: $where, orderBy: $orderBy, offset: $offset, limit: $limit) {\n      id\n      token0 {\n        id\n        symbol\n        name\n        decimals\n        totalSupply\n        circulationSupply\n        holders\n        tokenPicture\n        tokenMetrics {\n          id\n          tokenAddress\n          priceUSD\n          priceETH\n          price24hDelta\n          marketCapUSD\n          fdv\n          tradeVolume24h\n          tradeVolumeUSD24h\n          tradeVolumeETH24h\n          txCount24h\n          txCountTotal\n          totalLiquidityAllPairs\n          totalLiquidityAllPairsUSD\n          lastUpdatedAt\n          lastUpdatedAtBlockTimestamp\n        }\n        factoryAddress\n        lastUpdatedAt\n        lastUpdatedAtBlockTimestamp\n      }\n      token1 {\n        id\n        symbol\n        name\n        decimals\n        totalSupply\n        circulationSupply\n        holders\n        tokenPicture\n        tokenMetrics {\n          id\n          tokenAddress\n          priceUSD\n          priceETH\n          price24hDelta\n          marketCapUSD\n          fdv\n          tradeVolume24h\n          tradeVolumeUSD24h\n          tradeVolumeETH24h\n          txCount24h\n          txCountTotal\n          totalLiquidityAllPairs\n          totalLiquidityAllPairsUSD\n          lastUpdatedAt\n          lastUpdatedAtBlockTimestamp\n        }\n        factoryAddress\n        lastUpdatedAt\n        lastUpdatedAtBlockTimestamp\n      }\n      token0Id\n      token1Id\n      reserve0\n      reserve1\n      liquidityUSD\n      liquidity24hDelta\n      lpTotalSupply\n      lpTotalLocked\n      lpDecimals\n      token0Price\n      token1Price\n      txCount24h\n      txCountTotal\n      tradeVolume24h\n      tradeVolumeUSD24h\n      tradeVolumeETH24h\n      tradeVolume24hDelta\n      fees24h\n      feesUSD24h\n      feesETH24h\n      fees24hDelta\n      createdAtTimestamp\n      createdAtBlockNumber\n      liquidityProviderCount\n      factoryAddress\n      lastUpdatedAt\n      lastUpdatedAtBlockTimestamp\n    }\n  }\n':
    types.PairsDocument,
  '\n  query CurrentLiquidityPositions(\n    $where: CurrentLiquidityPositionWhereInput\n    $orderBy: [CurrentLiquidityPositionOrderByInput!]\n    $offset: Int\n    $limit: Int\n  ) {\n    currentLiquidityPositions(\n      where: $where\n      orderBy: $orderBy\n      offset: $offset\n      limit: $limit\n    ) {\n      id\n      user {\n        id\n        usdSwapped\n        swapsAmount\n        lastUpdatedAt\n        lastUpdatedAtBlockTimestamp\n      }\n      pair {\n        id\n        token0 {\n          id\n          symbol\n          name\n          decimals\n          totalSupply\n          circulationSupply\n          holders\n          tokenMetrics {\n            id\n            tokenAddress\n            priceUSD\n            priceETH\n            price24hDelta\n            marketCapUSD\n            fdv\n            tradeVolume24h\n            tradeVolumeUSD24h\n            tradeVolumeETH24h\n            txCount24h\n            txCountTotal\n            totalLiquidityAllPairs\n            totalLiquidityAllPairsUSD\n            lastUpdatedAt\n            lastUpdatedAtBlockTimestamp\n          }\n          factoryAddress\n          lastUpdatedAt\n          lastUpdatedAtBlockTimestamp\n        }\n        token1 {\n          id\n          symbol\n          name\n          decimals\n          totalSupply\n          circulationSupply\n          holders\n          tokenMetrics {\n            id\n            tokenAddress\n            priceUSD\n            priceETH\n            price24hDelta\n            marketCapUSD\n            fdv\n            tradeVolume24h\n            tradeVolumeUSD24h\n            tradeVolumeETH24h\n            txCount24h\n            txCountTotal\n            totalLiquidityAllPairs\n            totalLiquidityAllPairsUSD\n            lastUpdatedAt\n            lastUpdatedAtBlockTimestamp\n          }\n          factoryAddress\n          lastUpdatedAt\n          lastUpdatedAtBlockTimestamp\n        }\n        token0Id\n        token1Id\n        reserve0\n        reserve1\n        liquidityUSD\n        liquidity24hDelta\n        lpTotalSupply\n        lpTotalLocked\n        lpDecimals\n        token0Price\n        token1Price\n        txCount24h\n        txCountTotal\n        tradeVolume24h\n        tradeVolumeUSD24h\n        tradeVolumeETH24h\n        tradeVolume24hDelta\n        fees24h\n        feesUSD24h\n        feesETH24h\n        fees24hDelta\n        createdAtTimestamp\n        createdAtBlockNumber\n        liquidityProviderCount\n        factoryAddress\n        lastUpdatedAt\n        lastUpdatedAtBlockTimestamp\n      }\n      liquidityTokenBalance\n      lastUpdatedAt\n      lastUpdatedAtBlockTimestamp\n    }\n  }\n':
    types.CurrentLiquidityPositionsDocument,
};

/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 *
 *
 * @example
 * ```ts
 * const query = graphql(`query GetUser($id: ID!) { user(id: $id) { name } }`);
 * ```
 *
 * The query argument is unknown!
 * Please regenerate the types.
 */
export function graphql(source: string): unknown;

/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(
  source: '\n  query HistoricalPairMetrics(\n    $where: HistoricalPairMetricsWhereInput\n    $orderBy: [HistoricalPairMetricsOrderByInput!]\n  ) {\n    historicalPairMetrics(where: $where, orderBy: $orderBy, limit: 350) {\n      id\n      date\n      pairAddress\n      token0\n      token1\n      reserve0\n      reserve1\n      liquidityUSD\n      lpTotalSupply\n      lpTotalLocked\n      token0Price\n      token1Price\n      txCount24h\n      txCountTotal\n      liquidityProviderCount\n      lastUpdatedAt\n      lastUpdatedAtBlockTimestamp\n    }\n  }\n',
): (typeof documents)['\n  query HistoricalPairMetrics(\n    $where: HistoricalPairMetricsWhereInput\n    $orderBy: [HistoricalPairMetricsOrderByInput!]\n  ) {\n    historicalPairMetrics(where: $where, orderBy: $orderBy, limit: 350) {\n      id\n      date\n      pairAddress\n      token0\n      token1\n      reserve0\n      reserve1\n      liquidityUSD\n      lpTotalSupply\n      lpTotalLocked\n      token0Price\n      token1Price\n      txCount24h\n      txCountTotal\n      liquidityProviderCount\n      lastUpdatedAt\n      lastUpdatedAtBlockTimestamp\n    }\n  }\n'];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(
  source: '\n  query PairById($pairByIdId: String!) {\n    pairById(id: $pairByIdId) {\n      id\n      token0 {\n        id\n        symbol\n        name\n        decimals\n        totalSupply\n        circulationSupply\n        holders\n        tokenPicture\n        tokenMetrics {\n          id\n          tokenAddress\n          priceUSD\n          priceETH\n          price24hDelta\n          marketCapUSD\n          fdv\n          tradeVolume24h\n          tradeVolumeUSD24h\n          tradeVolumeETH24h\n          txCount24h\n          txCountTotal\n          totalLiquidityAllPairs\n          totalLiquidityAllPairsUSD\n          lastUpdatedAt\n          lastUpdatedAtBlockTimestamp\n        }\n        factoryAddress\n        lastUpdatedAt\n        lastUpdatedAtBlockTimestamp\n      }\n      token1 {\n        id\n        symbol\n        name\n        tokenPicture\n        decimals\n        totalSupply\n        circulationSupply\n        holders\n        tokenMetrics {\n          id\n          tokenAddress\n          priceUSD\n          priceETH\n          price24hDelta\n          marketCapUSD\n          fdv\n          tradeVolume24h\n          tradeVolumeUSD24h\n          tradeVolumeETH24h\n          txCount24h\n          txCountTotal\n          totalLiquidityAllPairs\n          totalLiquidityAllPairsUSD\n          lastUpdatedAt\n          lastUpdatedAtBlockTimestamp\n        }\n        factoryAddress\n        lastUpdatedAt\n        lastUpdatedAtBlockTimestamp\n      }\n      token0Id\n      token1Id\n      reserve0\n      reserve1\n      liquidityUSD\n      liquidity24hDelta\n      lpTotalSupply\n      lpTotalLocked\n      lpDecimals\n      token0Price\n      token1Price\n      txCount24h\n      txCountTotal\n      tradeVolume24h\n      tradeVolumeUSD24h\n      tradeVolumeETH24h\n      tradeVolume24hDelta\n      fees24h\n      feesUSD24h\n      feesETH24h\n      fees24hDelta\n      createdAtTimestamp\n      createdAtBlockNumber\n      liquidityProviderCount\n      factoryAddress\n      lastUpdatedAt\n      lastUpdatedAtBlockTimestamp\n    }\n  }\n',
): (typeof documents)['\n  query PairById($pairByIdId: String!) {\n    pairById(id: $pairByIdId) {\n      id\n      token0 {\n        id\n        symbol\n        name\n        decimals\n        totalSupply\n        circulationSupply\n        holders\n        tokenPicture\n        tokenMetrics {\n          id\n          tokenAddress\n          priceUSD\n          priceETH\n          price24hDelta\n          marketCapUSD\n          fdv\n          tradeVolume24h\n          tradeVolumeUSD24h\n          tradeVolumeETH24h\n          txCount24h\n          txCountTotal\n          totalLiquidityAllPairs\n          totalLiquidityAllPairsUSD\n          lastUpdatedAt\n          lastUpdatedAtBlockTimestamp\n        }\n        factoryAddress\n        lastUpdatedAt\n        lastUpdatedAtBlockTimestamp\n      }\n      token1 {\n        id\n        symbol\n        name\n        tokenPicture\n        decimals\n        totalSupply\n        circulationSupply\n        holders\n        tokenMetrics {\n          id\n          tokenAddress\n          priceUSD\n          priceETH\n          price24hDelta\n          marketCapUSD\n          fdv\n          tradeVolume24h\n          tradeVolumeUSD24h\n          tradeVolumeETH24h\n          txCount24h\n          txCountTotal\n          totalLiquidityAllPairs\n          totalLiquidityAllPairsUSD\n          lastUpdatedAt\n          lastUpdatedAtBlockTimestamp\n        }\n        factoryAddress\n        lastUpdatedAt\n        lastUpdatedAtBlockTimestamp\n      }\n      token0Id\n      token1Id\n      reserve0\n      reserve1\n      liquidityUSD\n      liquidity24hDelta\n      lpTotalSupply\n      lpTotalLocked\n      lpDecimals\n      token0Price\n      token1Price\n      txCount24h\n      txCountTotal\n      tradeVolume24h\n      tradeVolumeUSD24h\n      tradeVolumeETH24h\n      tradeVolume24hDelta\n      fees24h\n      feesUSD24h\n      feesETH24h\n      fees24hDelta\n      createdAtTimestamp\n      createdAtBlockNumber\n      liquidityProviderCount\n      factoryAddress\n      lastUpdatedAt\n      lastUpdatedAtBlockTimestamp\n    }\n  }\n'];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(
  source: '\n  query GetPairPricesQuery(\n    $maxPoints: Int!\n    $from: String!\n    $to: String!\n    $token0Address: String!\n    $token1Address: String!\n  ) {\n    pairPrices(\n      maxPoints: $maxPoints\n      to: $to\n      from: $from\n      token0Address: $token0Address\n      token1Address: $token1Address\n    ) {\n      token0 {\n        tokenAddress\n        tokenPrice\n        tokenPriceUsd\n      }\n      token1 {\n        tokenAddress\n        tokenPrice\n        tokenPriceUsd\n      }\n      timestamp\n    }\n  }\n',
): (typeof documents)['\n  query GetPairPricesQuery(\n    $maxPoints: Int!\n    $from: String!\n    $to: String!\n    $token0Address: String!\n    $token1Address: String!\n  ) {\n    pairPrices(\n      maxPoints: $maxPoints\n      to: $to\n      from: $from\n      token0Address: $token0Address\n      token1Address: $token1Address\n    ) {\n      token0 {\n        tokenAddress\n        tokenPrice\n        tokenPriceUsd\n      }\n      token1 {\n        tokenAddress\n        tokenPrice\n        tokenPriceUsd\n      }\n      timestamp\n    }\n  }\n'];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(
  source: '\n  query Pairs(\n    $where: PairWhereInput\n    $orderBy: [PairOrderByInput!]\n    $offset: Int\n    $limit: Int\n  ) {\n    pairs(where: $where, orderBy: $orderBy, offset: $offset, limit: $limit) {\n      id\n      token0 {\n        id\n        symbol\n        name\n        decimals\n        totalSupply\n        circulationSupply\n        holders\n        tokenPicture\n        tokenMetrics {\n          id\n          tokenAddress\n          priceUSD\n          priceETH\n          price24hDelta\n          marketCapUSD\n          fdv\n          tradeVolume24h\n          tradeVolumeUSD24h\n          tradeVolumeETH24h\n          txCount24h\n          txCountTotal\n          totalLiquidityAllPairs\n          totalLiquidityAllPairsUSD\n          lastUpdatedAt\n          lastUpdatedAtBlockTimestamp\n        }\n        factoryAddress\n        lastUpdatedAt\n        lastUpdatedAtBlockTimestamp\n      }\n      token1 {\n        id\n        symbol\n        name\n        decimals\n        totalSupply\n        circulationSupply\n        holders\n        tokenPicture\n        tokenMetrics {\n          id\n          tokenAddress\n          priceUSD\n          priceETH\n          price24hDelta\n          marketCapUSD\n          fdv\n          tradeVolume24h\n          tradeVolumeUSD24h\n          tradeVolumeETH24h\n          txCount24h\n          txCountTotal\n          totalLiquidityAllPairs\n          totalLiquidityAllPairsUSD\n          lastUpdatedAt\n          lastUpdatedAtBlockTimestamp\n        }\n        factoryAddress\n        lastUpdatedAt\n        lastUpdatedAtBlockTimestamp\n      }\n      token0Id\n      token1Id\n      reserve0\n      reserve1\n      liquidityUSD\n      liquidity24hDelta\n      lpTotalSupply\n      lpTotalLocked\n      lpDecimals\n      token0Price\n      token1Price\n      txCount24h\n      txCountTotal\n      tradeVolume24h\n      tradeVolumeUSD24h\n      tradeVolumeETH24h\n      tradeVolume24hDelta\n      fees24h\n      feesUSD24h\n      feesETH24h\n      fees24hDelta\n      createdAtTimestamp\n      createdAtBlockNumber\n      liquidityProviderCount\n      factoryAddress\n      lastUpdatedAt\n      lastUpdatedAtBlockTimestamp\n    }\n  }\n',
): (typeof documents)['\n  query Pairs(\n    $where: PairWhereInput\n    $orderBy: [PairOrderByInput!]\n    $offset: Int\n    $limit: Int\n  ) {\n    pairs(where: $where, orderBy: $orderBy, offset: $offset, limit: $limit) {\n      id\n      token0 {\n        id\n        symbol\n        name\n        decimals\n        totalSupply\n        circulationSupply\n        holders\n        tokenPicture\n        tokenMetrics {\n          id\n          tokenAddress\n          priceUSD\n          priceETH\n          price24hDelta\n          marketCapUSD\n          fdv\n          tradeVolume24h\n          tradeVolumeUSD24h\n          tradeVolumeETH24h\n          txCount24h\n          txCountTotal\n          totalLiquidityAllPairs\n          totalLiquidityAllPairsUSD\n          lastUpdatedAt\n          lastUpdatedAtBlockTimestamp\n        }\n        factoryAddress\n        lastUpdatedAt\n        lastUpdatedAtBlockTimestamp\n      }\n      token1 {\n        id\n        symbol\n        name\n        decimals\n        totalSupply\n        circulationSupply\n        holders\n        tokenPicture\n        tokenMetrics {\n          id\n          tokenAddress\n          priceUSD\n          priceETH\n          price24hDelta\n          marketCapUSD\n          fdv\n          tradeVolume24h\n          tradeVolumeUSD24h\n          tradeVolumeETH24h\n          txCount24h\n          txCountTotal\n          totalLiquidityAllPairs\n          totalLiquidityAllPairsUSD\n          lastUpdatedAt\n          lastUpdatedAtBlockTimestamp\n        }\n        factoryAddress\n        lastUpdatedAt\n        lastUpdatedAtBlockTimestamp\n      }\n      token0Id\n      token1Id\n      reserve0\n      reserve1\n      liquidityUSD\n      liquidity24hDelta\n      lpTotalSupply\n      lpTotalLocked\n      lpDecimals\n      token0Price\n      token1Price\n      txCount24h\n      txCountTotal\n      tradeVolume24h\n      tradeVolumeUSD24h\n      tradeVolumeETH24h\n      tradeVolume24hDelta\n      fees24h\n      feesUSD24h\n      feesETH24h\n      fees24hDelta\n      createdAtTimestamp\n      createdAtBlockNumber\n      liquidityProviderCount\n      factoryAddress\n      lastUpdatedAt\n      lastUpdatedAtBlockTimestamp\n    }\n  }\n'];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(
  source: '\n  query CurrentLiquidityPositions(\n    $where: CurrentLiquidityPositionWhereInput\n    $orderBy: [CurrentLiquidityPositionOrderByInput!]\n    $offset: Int\n    $limit: Int\n  ) {\n    currentLiquidityPositions(\n      where: $where\n      orderBy: $orderBy\n      offset: $offset\n      limit: $limit\n    ) {\n      id\n      user {\n        id\n        usdSwapped\n        swapsAmount\n        lastUpdatedAt\n        lastUpdatedAtBlockTimestamp\n      }\n      pair {\n        id\n        token0 {\n          id\n          symbol\n          name\n          decimals\n          totalSupply\n          circulationSupply\n          holders\n          tokenMetrics {\n            id\n            tokenAddress\n            priceUSD\n            priceETH\n            price24hDelta\n            marketCapUSD\n            fdv\n            tradeVolume24h\n            tradeVolumeUSD24h\n            tradeVolumeETH24h\n            txCount24h\n            txCountTotal\n            totalLiquidityAllPairs\n            totalLiquidityAllPairsUSD\n            lastUpdatedAt\n            lastUpdatedAtBlockTimestamp\n          }\n          factoryAddress\n          lastUpdatedAt\n          lastUpdatedAtBlockTimestamp\n        }\n        token1 {\n          id\n          symbol\n          name\n          decimals\n          totalSupply\n          circulationSupply\n          holders\n          tokenMetrics {\n            id\n            tokenAddress\n            priceUSD\n            priceETH\n            price24hDelta\n            marketCapUSD\n            fdv\n            tradeVolume24h\n            tradeVolumeUSD24h\n            tradeVolumeETH24h\n            txCount24h\n            txCountTotal\n            totalLiquidityAllPairs\n            totalLiquidityAllPairsUSD\n            lastUpdatedAt\n            lastUpdatedAtBlockTimestamp\n          }\n          factoryAddress\n          lastUpdatedAt\n          lastUpdatedAtBlockTimestamp\n        }\n        token0Id\n        token1Id\n        reserve0\n        reserve1\n        liquidityUSD\n        liquidity24hDelta\n        lpTotalSupply\n        lpTotalLocked\n        lpDecimals\n        token0Price\n        token1Price\n        txCount24h\n        txCountTotal\n        tradeVolume24h\n        tradeVolumeUSD24h\n        tradeVolumeETH24h\n        tradeVolume24hDelta\n        fees24h\n        feesUSD24h\n        feesETH24h\n        fees24hDelta\n        createdAtTimestamp\n        createdAtBlockNumber\n        liquidityProviderCount\n        factoryAddress\n        lastUpdatedAt\n        lastUpdatedAtBlockTimestamp\n      }\n      liquidityTokenBalance\n      lastUpdatedAt\n      lastUpdatedAtBlockTimestamp\n    }\n  }\n',
): (typeof documents)['\n  query CurrentLiquidityPositions(\n    $where: CurrentLiquidityPositionWhereInput\n    $orderBy: [CurrentLiquidityPositionOrderByInput!]\n    $offset: Int\n    $limit: Int\n  ) {\n    currentLiquidityPositions(\n      where: $where\n      orderBy: $orderBy\n      offset: $offset\n      limit: $limit\n    ) {\n      id\n      user {\n        id\n        usdSwapped\n        swapsAmount\n        lastUpdatedAt\n        lastUpdatedAtBlockTimestamp\n      }\n      pair {\n        id\n        token0 {\n          id\n          symbol\n          name\n          decimals\n          totalSupply\n          circulationSupply\n          holders\n          tokenMetrics {\n            id\n            tokenAddress\n            priceUSD\n            priceETH\n            price24hDelta\n            marketCapUSD\n            fdv\n            tradeVolume24h\n            tradeVolumeUSD24h\n            tradeVolumeETH24h\n            txCount24h\n            txCountTotal\n            totalLiquidityAllPairs\n            totalLiquidityAllPairsUSD\n            lastUpdatedAt\n            lastUpdatedAtBlockTimestamp\n          }\n          factoryAddress\n          lastUpdatedAt\n          lastUpdatedAtBlockTimestamp\n        }\n        token1 {\n          id\n          symbol\n          name\n          decimals\n          totalSupply\n          circulationSupply\n          holders\n          tokenMetrics {\n            id\n            tokenAddress\n            priceUSD\n            priceETH\n            price24hDelta\n            marketCapUSD\n            fdv\n            tradeVolume24h\n            tradeVolumeUSD24h\n            tradeVolumeETH24h\n            txCount24h\n            txCountTotal\n            totalLiquidityAllPairs\n            totalLiquidityAllPairsUSD\n            lastUpdatedAt\n            lastUpdatedAtBlockTimestamp\n          }\n          factoryAddress\n          lastUpdatedAt\n          lastUpdatedAtBlockTimestamp\n        }\n        token0Id\n        token1Id\n        reserve0\n        reserve1\n        liquidityUSD\n        liquidity24hDelta\n        lpTotalSupply\n        lpTotalLocked\n        lpDecimals\n        token0Price\n        token1Price\n        txCount24h\n        txCountTotal\n        tradeVolume24h\n        tradeVolumeUSD24h\n        tradeVolumeETH24h\n        tradeVolume24hDelta\n        fees24h\n        feesUSD24h\n        feesETH24h\n        fees24hDelta\n        createdAtTimestamp\n        createdAtBlockNumber\n        liquidityProviderCount\n        factoryAddress\n        lastUpdatedAt\n        lastUpdatedAtBlockTimestamp\n      }\n      liquidityTokenBalance\n      lastUpdatedAt\n      lastUpdatedAtBlockTimestamp\n    }\n  }\n'];

export function graphql(source: string) {
  return (documents as any)[source] ?? {};
}

export type DocumentType<TDocumentNode extends DocumentNode<any, any>> =
  TDocumentNode extends DocumentNode<infer TType, any> ? TType : never;